---
title: "asdasdas"
author: 'Grupo #'
date: "11/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
load("data_corregida.RData")
```

```{r}
summary(data_corregida)
```



```{r}
calculo_indice <- data_corregida %>% group_by(BARRIO,COMUNA) %>%
          summarise(cantidad_accidentes = n(),
                    Choque = length(CLASE_ACCIDENTE[CLASE_ACCIDENTE == "Choque"]),
                    Atropello = length(CLASE_ACCIDENTE[CLASE_ACCIDENTE == "Atropello"]),
                    Caida_de_Ocupante = length(CLASE_ACCIDENTE[CLASE_ACCIDENTE == "Caída de Ocupante"]),
                    Valor = (0.25 * Choque + 0.25 * Atropello + 0.5 * Caida_de_Ocupante)/cantidad_accidentes)

calculo_indice <- calculo_indice[calculo_indice$BARRIO!='""',]

```




```{r}
aux <- subset(calculo_indice,select = c(Valor))

```

```{r}
agrupamiento <- kmeans(aux, centers = 4)
```
```{r}
calculo_indice$Riesgo <- agrupamiento$cluster
```

```{r}
#Se crean los grupos de acuerdo a la clasificación obtenida
grupo1 <- subset(calculo_indice, calculo_indice$Riesgo==1)
grupo1_Barrio <- grupo1$BARRIO
grupo1 <- subset(grupo1, select = -c(BARRIO,COMUNA))

grupo2 <- subset(calculo_indice, calculo_indice$Riesgo==2)
grupo2_Barrio  <- grupo2$BARRIO
grupo2 <- subset(grupo2, select = -c(BARRIO,COMUNA))

grupo3 <- subset(calculo_indice, calculo_indice$Riesgo==3)
grupo3_Barrio  <- grupo3$BARRIO
grupo3 <- subset(grupo3, select = -c(BARRIO,COMUNA))

grupo4 <- subset(calculo_indice, calculo_indice$Riesgo==4)
grupo4_Barrio  <- grupo4$BARRIO
grupo4 <- subset(grupo4, select = -c(BARRIO,COMUNA))

```

```{r}
summary(grupo1)
```

```{r}
summary(grupo2)
```
```{r}
summary(grupo3)
```
```{r}
summary(grupo4)
```
```{r}
calculo_indice <- calculo_indice %>% 
  mutate(Riesgo = recode(Riesgo,
                          "1" = "Muy Alto",
                          "2" = "Alto",
                          "3" = "Bajo",
                          "4" = "Medio"))
```

```{r}
calculo_indice <- subset(calculo_indice, select = -c(cantidad_accidentes,Choque,Atropello,Caida_de_Ocupante,Valor))
```
```{r}
save(calculo_indice, file = "calculo_indice.RData")
```

